### PR TITLE
fix: fix statusMatrix with win32 linebreaks

### LINKED ISSUE #1904: StatusMatrix results are different on Windows and Linux
I recently discovered that the results of statusMatrix are different on Windows and Linux.

`unmodified` files (`[1,1,1]`) are listed on windows as `modified, unstaged` (`[ 1, 2, 1 ]`)

See: https://github.com/jayree/iso-win-test/actions/runs/8846190106/job/24291562894

### PR DESCRIPTION
**Pull request by jayree**
## I'm fixing a bug or typo

fixes #1904

### CODE REVIEW

File: src/api/add.js [hunk 1]
```diff
@@ -117,11 +118,21 @@ async function addToIndex({
...
+            encoding: 'utf8',
+            autocrlf,
+          })
       if (object === null) throw new NotFoundError(currentFilepath)
-      const oid = await _writeObject({ fs, gitdir, type: 'blob', object })
+      const oid = await _writeObject({
+        fs,
+        gitdir,
+        type: 'blob',
+        object: Buffer.from(object),
```
Comment (jcubic) [inline src/api/add.js:134]: We wanted to get rid of Buffer, please don't add yet another use of it if possible.

File: src/models/GitWalkerFs.js [hunk 2]
```diff
@@ -94,17 +95,22 @@ export class GitWalkerFs {
...
+          encoding: 'utf8',
+          autocrlf,
+        })
         // workaround for a BrowserFS edge case
         entry._actualSize = content.length
         if (entry._stat && entry._stat.size === -1) {
           entry._stat.size = entry._actualSize
         }
-        entry._content = new Uint8Array(content)
+        entry._content = new Uint8Array(Buffer.from(content))
```
Comment (jcubic) [inline src/models/GitWalkerFs.js:113]: Please don't use `Buffer`

**Review by jcubic — CHANGES_REQUESTED** [review]
