### PR TITLE
fix: avoid side effects of 'annotatedTag' and 'commit'

### LINKED ISSUE #642: Some fixes to 'annotatedTag' and 'commit'
https://github.com/isomorphic-git/isomorphic-git/pull/621#issuecomment-446284927

> I just noticed this in the code:
> 
> ```
> tagger.timestamp !== undefined && tagger.timestamp !== null
> ```
> That's functionally equivalent to:
> 
> ```
> tagger.timestamp != null
> ```
> There's no reason to check for exactly null and undefined.

https://github.com/isomorphic-git/isomorphic-git/pull/621#issuecomment-446286045

> I also noticed that if the tagger object passed in is missing name or email, the object is modified directly. I don't think a function should have side effects.
> 
> And one more thing. I think the message should default to the tag name (i.e., ref) instead of being blank. That's a pretty typical git practice.

Thanks @mojavelinux! And sorry I didn't notice these viewpoints.

### PR DESCRIPTION
**Pull request by yuhr**
## I'm fixing a bug or typo

- [x] <s>if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README</s>
- [x] squash merge the PR with commit message "fix: [Description of fix]"

Closes #642

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for c941a5d46157101ba5298289753a71b7a265b7f3:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 241 | 1 | 0 | 1 min 7.083 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 241 | 1 | 0 | 1 min 46.61 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 241 | 1 | 0 | 3 mins 3.388 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 241 | 1 | 0 | 3 mins 14.139 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 241 | 1 | 0 | 3 mins 48.004 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 240 | 1 | 1 | 8 mins 29.557 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for c941a5d46157101ba5298289753a71b7a265b7f3:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Mobile Safari 11.0.0 (iOS 11.2.0) | 241 | 1 | 0 | 5 mins 58.097 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 648c4bdcc8b711d6073d24201d8c145f70ccc6e2:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 241 | 1 | 0 | 2 mins 52.947 secs | false | undefined |

File: src/commands/commit.js [hunk 1]
```diff
@@ -28,26 +28,40 @@ export async function commit ({
...
+
+    // Fill in missing arguments with default values
+    author = { ...author }
+    author.name = author.name || await config({ fs, gitdir, path: 'user.name' })
+    author.email = author.email || await config({ fs, gitdir, path: 'user.email' })
+    if (author.name === undefined || author.email === undefined) {
+      throw new GitError(E.MissingAuthorError)
+    }
+
+    committer = { ...(committer || author) }
```
[the remark this answers is not in the document]
Comment (yuhr) [reply src/commands/commit.js]: Well this would be another issue...

**Comment by wmhilton** [comment]
Let's go ahead and abstract this into a function in `utils`. Something that takes in an incomplete `author` and spits out a complete `author`. Then we can just call that utility in both `commit` and `annotatedTag`.

File: src/commands/annotatedTag.js [hunk 2]
```diff
@@ -59,36 +59,27 @@ export async function annotatedTag ({
...
 
     // Fill in missing arguments with default values
-    if (tagger === undefined) tagger = {}
-    if (tagger.name === undefined) {
-      tagger.name = await config({ fs, gitdir, path: 'user.name' })
-    }
-    if (tagger.email === undefined) {
-      tagger.email = await config({ fs, gitdir, path: 'user.email' })
-    }
+    tagger = { ...tagger }
```
Comment (wmhilton) [inline src/commands/annotatedTag.js]: Unfortunately, we'll have to use Object.assign here. Too many people ran into issues with object spread. See https://gitter.im/isomorphic-git/Lobby?at=5bd8a0ed435c2a518e2cc779 for background.

Comment (wmhilton) [reply src/commands/annotatedTag.js]: Alternatively, you could use 
```js
const { name, email, date, timestamp, timezoneOffset } = tagger
```
if those variable names are all available in this scope. Probably can't do that for `commit` since it has both an author and a comitter to worry about... OH but if we put this in a `util` function then that doesn't matter. I kinda like that approach.

File: src/commands/annotatedTag.js [hunk 3]
```diff
@@ -59,36 +59,27 @@ export async function annotatedTag ({
...
+    tagger.name = tagger.name || await config({ fs, gitdir, path: 'user.name' })
+    tagger.email = tagger.email || await config({ fs, gitdir, path: 'user.email' })
     if (tagger.name === undefined || tagger.email === undefined) {
       throw new GitError(E.MissingAuthorError)
     }
 
-    const { type } = (await readObject({ fs, gitdir, oid }))
-    let taggerDateTime = tagger.date || new Date()
+    const taggerDateTime = tagger.date || new Date()
+    tagger.timestamp = tagger.timestamp != null
```
Comment (wmhilton) [inline src/commands/annotatedTag.js]: This needs to be `tagger.timestamp !== undefined && tagger.timestamp !== null` unfortunately. (I've challenged Dan to think of the edge case... it's probably easier to figure out why this is needed for `timezoneOffset`

File: src/commands/annotatedTag.js [hunk 4]
```diff
@@ -59,36 +59,27 @@ export async function annotatedTag ({
...
-            tagger.timestamp !== undefined && tagger.timestamp !== null
-              ? tagger.timestamp
-              : Math.floor(taggerDateTime.valueOf() / 1000),
-        timezoneOffset:
-            tagger.timezoneOffset !== undefined &&
-            tagger.timezoneOffset !== null
-              ? tagger.timezoneOffset
-              : taggerDateTime.getTimezoneOffset()
-      },
+      tagger,
```
Comment (wmhilton) [inline src/commands/annotatedTag.js]: with our utility function, this could be
```js
tagger: authorDateTime(tagger)
```
Maybe you can think of a better name. `populateNameEmailDateTimeAndZone`? `normalizeAuthorObject`?

File: src/commands/annotatedTag.js (hunk 3 above)
Comment (yuhr) [reply src/commands/annotatedTag.js]: Hmm, I'm totally not sure how loose equality works in this case, but I'll fix for now.

File: src/commands/annotatedTag.js (hunk 2 above)
Comment (yuhr) [reply src/commands/annotatedTag.js]: > Unfortunately, we'll have to use Object.assign here. Too many people ran into issues with object spread. See https://gitter.im/isomorphic-git/Lobby?at=5bd8a0ed435c2a518e2cc779 for background.

I see. I think this kind of terms should be written to `CONTRIBUTING.md` 😭

**Comment by yuhr** [comment]
I wapped up things, but now I've noticed there's another issue about how to treat properties of `author` and `committer` in multiple use cases of `commit` command... so, could you take a little look and merge this PR for now? Of course if it seems something's unresolved regarding to side effects or loose equality, I'll pursue that.

File: src/commands/annotatedTag.js (hunk 3 above)
Comment (wmhilton) [reply src/commands/annotatedTag.js]: (Apparently I also did not know how loose equality worked in this case. Dan schooled me!)

**Comment by wmhilton** [comment]
Looks great! Only things I changed was I noticed normalizeAuthorObject would throw if it couldn't destructure `author` so I gave it a default argument so you don't have to consciously pass it `author || {}` every time.

And I changed that loose inequality thing that was bugging Dan (since it turned out he was right).

**Comment by wmhilton** [comment]
Oh. And I'll make the default message = ref instead of = '' @mojavelinux
